export const HANDLER_REQUEST_USERS_SAVE     = 'HANDLER_REQUEST_USERS_SAVE';
export const HANDLER_REQUEST_USERS_DELETE   = 'HANDLER_REQUEST_USERS_DELETE';
export const HANDLER_REQUEST_USERS_UPDATE   = 'HANDLER_REQUEST_USERS_UPDATE';
export const HANDLER_REQUEST_USERS_CREATE   = 'HANDLER_REQUEST_USERS_CREATE';
